In [2]:
import pandas as pd
import numpy as np

In [16]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import iplot

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
df1 = pd.read_csv('/content/df1.csv')
df1.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  \
0                      4.0    Male        55.0             2.0       2.0   
1                      4.0  Female        54.0             2.0       3.0   
2                      3.0  Female        46.0             2.0       1.0   
3                      4.0  Female        66.0             3.0       1.0   
4                      3.0    Male        75.0             3.0       1.0   

                  JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  \
0   Laboratory Technician              4.0       Married         5126.0   
1  Manufacturing Director              3.0       Married         7756.0   
2      Research Scientist              2.0       Married         2368.0   
3      Research Scientist              4.0        Single         3310.0   
4   Laboratory Technician              4.0      Divorced         1951.0   

   MonthlyRate  NumCompaniesWorked  
0      15998.0                 1.0  
1      14199.0                 3.0  
2      23300.0                 1.0  
3       4488.0                 1.0  
4      10910.0                 1.0

In [5]:
df1.shape

(4449, 20)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4449 entries, 0 to 4448
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   EmployeeNumber           4449 non-null   int64  
 1   Age                      4449 non-null   float64
 2   BusinessTravel           4449 non-null   object 
 3   DailyRate                4449 non-null   float64
 4   Department               4449 non-null   object 
 5   DistanceFromHome         4449 non-null   float64
 6   Education                4449 non-null   float64
 7   EducationField           4449 non-null   object 
 8   EmployeeCount            4449 non-null   float64
 9   EnvironmentSatisfaction  4449 non-null   float64
 10  Gender                   4449 non-null   object 
 11  HourlyRate               4449 non-null   float64
 12  JobInvolvement           4449 non-null   float64
 13  JobLevel                 4449 non-null   float64
 14  JobRole                 

In [6]:
df2 = pd.read_csv('/content/df2.csv')
df2.head()

EmployeeNumber Over18 OverTime  PercentSalaryHike  PerformanceRating  \
0             104      Y      Yes               12.0                3.0   
1            1638      Y      Yes               19.0                3.0   
2             164      Y       No               19.0                3.0   
3             395      Y       No               21.0                4.0   
4              53      Y       No               12.0                3.0   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                       3.0           80.0               2.0   
1                       4.0           80.0               1.0   
2                       3.0           80.0               0.0   
3                       4.0           80.0               0.0   
4                       3.0           80.0               1.0   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0               10.0                    1.0              2.0            10.0   
1               10.0                    6.0              4.0             5.0   
2                5.0                    3.0              2.0             5.0   
3                5.0                    3.0              3.0             5.0   
4                1.0                    3.0              3.0             1.0   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                 8.0                      3.0                   0.0   
1                 4.0                      0.0                   2.0   
2                 4.0                      4.0                   3.0   
3                 3.0                      0.0                   2.0   
4                 0.0                      0.0                   0.0   

  Attrition  YearlyIncome  
0        No       61512.0  
1        No       93072.0  
2        No       28416.0  
3        No       39720.0  
4        No       23412.0

In [7]:
df2.shape

(4449, 17)

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4449 entries, 0 to 4448
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   EmployeeNumber            4449 non-null   int64  
 1   Over18                    4449 non-null   object 
 2   OverTime                  4449 non-null   object 
 3   PercentSalaryHike         4449 non-null   float64
 4   PerformanceRating         4449 non-null   float64
 5   RelationshipSatisfaction  4449 non-null   float64
 6   StandardHours             4449 non-null   float64
 7   StockOptionLevel          4449 non-null   float64
 8   TotalWorkingYears         4449 non-null   float64
 9   TrainingTimesLastYear     4449 non-null   float64
 10  WorkLifeBalance           4449 non-null   float64
 11  YearsAtCompany            4449 non-null   float64
 12  YearsInCurrentRole        4449 non-null   float64
 13  YearsSinceLastPromotion   4449 non-null   float64
 14  YearsWit

In [429]:
df = pd.merge(df1, df2, on='EmployeeNumber')

In [430]:
df.shape

(4449, 36)

In [431]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4449 entries, 0 to 4448
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   EmployeeNumber            4449 non-null   int64  
 1   Age                       4449 non-null   float64
 2   BusinessTravel            4449 non-null   object 
 3   DailyRate                 4449 non-null   float64
 4   Department                4449 non-null   object 
 5   DistanceFromHome          4449 non-null   float64
 6   Education                 4449 non-null   float64
 7   EducationField            4449 non-null   object 
 8   EmployeeCount             4449 non-null   float64
 9   EnvironmentSatisfaction   4449 non-null   float64
 10  Gender                    4449 non-null   object 
 11  HourlyRate                4449 non-null   float64
 12  JobInvolvement            4449 non-null   float64
 13  JobLevel                  4449 non-null   float64
 14  JobRole 

In [432]:
df.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  ... StockOptionLevel  TotalWorkingYears  \
0                      4.0  ...              2.0               10.0   
1                      4.0  ...              1.0               10.0   
2                      3.0  ...              0.0                5.0   
3                      4.0  ...              0.0                5.0   
4                      3.0  ...              1.0                1.0   

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                    1.0              2.0           10.0                 8.0   
1                    6.0              4.0            5.0                 4.0   
2                    3.0              2.0            5.0                 4.0   
3                    3.0              3.0            5.0                 3.0   
4                    3.0              3.0            1.0                 0.0   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  YearlyIncome  
0                     3.0                   0.0         No       61512.0  
1                     0.0                   2.0         No       93072.0  
2                     4.0                   3.0         No       28416.0  
3                     0.0                   2.0         No       39720.0  
4                     0.0                   0.0         No       23412.0  

[5 rows x 36 columns]

In [433]:
df.Attrition.unique()

array(['No', 'Yes', nan], dtype=object)

In [434]:
df = df.dropna(subset=['Attrition'])

In [435]:
df.Attrition.unique()

array(['No', 'Yes'], dtype=object)

In [436]:
df.shape

(4302, 36)

In [437]:
Attrition_dict = {'No':0, 'Yes':1}
df['Attrition']=df['Attrition'].map(Attrition_dict)

<ipython-input-437-dc7ff77ac07e>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [438]:
df.Attrition.unique()

array([0, 1])

In [439]:
df.Age.unique()

array([  30.,   38.,   26.,   28.,   35.,   34.,   32.,   42.,   40.,
         48.,   39.,   18.,   43.,   21.,   53.,   45.,   29.,   33.,
         41.,   24.,   37.,   50.,   36.,   52.,   47.,   31.,   49.,
         54.,   44.,   22.,   46.,   27.,   55.,   59.,   25.,   23.,
         56.,   20.,   60.,   51.,   58.,   19.,   57., 8825., 3628.,
       6287., 9330., 1107., 4454., 9155., 9890., 1189., 9195., 9014.,
       1136., 5582., 2404., 1541., 4510., 4322., 4988., 8388., 2530.,
       8901., 2852., 2459., 2982., 4973., 8534., 8314., 4130., 4328.,
       7952., 8699., 3147., 8889., 3871., 9531., 8167., 5257., 8136.,
       7390., 2993., 5672., 5933., 5614., 5007., 3095., 9219., 6749.,
       4515., 6715., 1141., 8949., 3636., 4805., 5959., 9384., 8042.,
       1423., 7056., 5116., 2667., 8703., 1126., 9612., 7845., 6998.,
       1788., 6727., 5377., 5565., 4558., 6506., 4591., 7662., 6510.,
       4985., 9581., 2095., 2275., 6399., 4935., 2698., 7617., 9661.,
       4834., 2242.,

In [440]:
df = df[df['Age'] <= 100]

In [441]:
df.Age.unique()

array([30., 38., 26., 28., 35., 34., 32., 42., 40., 48., 39., 18., 43.,
       21., 53., 45., 29., 33., 41., 24., 37., 50., 36., 52., 47., 31.,
       49., 54., 44., 22., 46., 27., 55., 59., 25., 23., 56., 20., 60.,
       51., 58., 19., 57.])

In [442]:
df.BusinessTravel.unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [443]:
df = df.join(pd.get_dummies(df["BusinessTravel"], drop_first=True)).drop("BusinessTravel", axis=1)

In [444]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'YearlyIncome',
       'Travel_Frequently', 'Travel_Rarely'],
      dtype='object')

In [445]:
df.DailyRate.unique()

array([ 852.,  397.,  841., 1117.,  464., 1107., 1018.,  269.,  296.,
        989.,  855., 1181.,  895.,  827.,  977.,  544.,  244.,  995.,
       1343., 1282.,  153.,  280.,  404., 1265.,  252., 1496.,  306.,
        128.,  529.,  553.,  572.,  482.,  471.,  509.,  130.,  506.,
        329.,  367., 1219.,  746., 1322.,  969., 1271., 1158.,  688.,
        319.,  371., 1336.,  107.,  448.,  359.,  625., 1017.,  835.,
       1050.,  523., 1064., 1128.,  928., 1319.,  932.,  809., 1376.,
        253.,  336.,  884., 1385.,  945.,  118., 1231.,  426.,  737.,
       1442.,  853.,  557.,  377.,  616., 1398., 1138.,  531.,  138.,
       1377., 1240., 1400., 1001., 1082., 1171.,  136.,  218.,  452.,
       1397., 1192.,  944.,  408., 1040., 1329., 1416., 1125., 1144.,
        442., 1157.,  438.,  147.,  140.,  240.,  202., 1297.,  486.,
       1146.,  150., 1404., 1206., 1172.,  771., 1167.,  441., 1141.,
        715.,  891.,  282., 1425., 1371.,  170.,  650., 1212.,  638.,
       1255., 1099.,

In [446]:
df.Department.unique()

array(['Research & Development', 'Human Resources', 'Sales'], dtype=object)

In [447]:
df = df.join(pd.get_dummies(df["Department"], drop_first=True)).drop("Department", axis=1)

In [448]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EducationField', 'EmployeeCount', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition',
       'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales'],
      dtype='object')

In [449]:
df.DistanceFromHome.unique()

array([1.00000e+00, 2.00000e+00, 6.00000e+00, 8.00000e+00, 4.00000e+00,
       9.00000e+00, 3.00000e+00, 5.00000e+00, 2.20000e+01, 2.60000e+01,
       1.00000e+01, 1.20000e+01, 7.00000e+00, 2.50000e+01, 2.90000e+01,
       1.80000e+01, 2.40000e+01, 2.80000e+01, 1.60000e+01, 1.90000e+01,
       1.30000e+01, 2.00000e+01, 1.10000e+01, 2.30000e+01, 2.10000e+01,
       1.50000e+01, 1.40000e+01, 1.70000e+01, 2.70000e+01, 3.02984e+05,
       6.29986e+05, 8.87003e+05, 9.18326e+05, 9.97422e+05, 8.52749e+05,
       6.79106e+05, 3.04698e+05, 7.72706e+05, 2.59089e+05, 9.92947e+05,
       2.53620e+05, 8.86117e+05, 8.60358e+05, 5.47308e+05, 1.93929e+05,
       9.63929e+05, 8.09361e+05, 1.40916e+05, 8.25100e+05, 4.18093e+05,
       7.16417e+05, 5.46730e+05, 2.42839e+05, 7.43173e+05, 1.50886e+05,
       9.46786e+05, 6.07220e+05, 5.60047e+05, 8.40183e+05, 5.88585e+05,
       4.79723e+05, 3.02239e+05, 9.99590e+05, 1.35607e+05, 3.27380e+05,
       5.16738e+05, 3.80120e+05, 2.89540e+05, 4.70836e+05, 6.364

In [450]:
df.Education.unique()

array([1., 2., 3., 4., 5.])

In [451]:
df.EducationField.unique()

array(['Life Sciences', 'Medical', 'Other', 'Technical Degree',
       'Marketing', 'Human Resources'], dtype=object)

In [452]:
df = df.join(pd.get_dummies(df["EducationField"], drop_first=True)).drop("EducationField", axis=1)

In [453]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'YearlyIncome',
       'Travel_Frequently', 'Travel_Rarely', 'Research & Development', 'Sales',
       'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree'],
      dtype='object')

In [454]:
df.EmployeeCount.unique()

array([1.])

In [455]:
df = df.drop(['EmployeeCount'] ,axis=1)

In [456]:
df.EnvironmentSatisfaction.unique()

array([4., 3., 1., 2.])

In [457]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [458]:
Gender_dict = {'Male':0, 'Female':1}
df['Gender']=df['Gender'].map(Gender_dict)

In [459]:
df.Gender.unique()

array([0, 1])

In [460]:
df.HourlyRate.unique()

array([ 55.,  54.,  46.,  66.,  75.,  52.,  39.,  56.,  33.,  82.,  45.,
        70.,  97.,  77.,  40.,  49.,  58.,  73.,  43.,  98.,  95.,  41.,
       100.,  84.,  79.,  74.,  90.,  96.,  91.,  32.,  88.,  86.,  76.,
        35.,  94.,  83.,  65.,  42.,  31.,  51.,  36.,  80.,  69.,  99.,
        48.,  89.,  81.,  61.,  92.,  59.,  44.,  47.,  53.,  34.,  60.,
        78.,  30.,  68.,  37.,  87.,  50.,  63.,  72.,  38.,  71.,  64.,
        85.,  57.,  67.,  62.,  93.])

In [461]:
df.JobInvolvement.unique()

array([2., 3., 1., 4.])

In [462]:
df.JobLevel.unique()

array([2., 3., 1., 5., 4.])

In [463]:
df.JobRole.unique()

array(['Laboratory Technician', 'Manufacturing Director',
       'Research Scientist', 'Human Resources', 'Research Director',
       'Sales Representative', 'Manager', 'Healthcare Representative',
       'Sales Executive'], dtype=object)

In [464]:
df = df.join(pd.get_dummies(df["JobRole"], drop_first=True)).drop("JobRole", axis=1)

In [465]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'Attrition', 'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales', 'Life Sciences', 'Marketing',
       'Medical', 'Other', 'Technical Degree', 'Human Resources',
       'Laboratory Technician', 'Manager', 'Manufacturing Director',
       'Research Director', 'Research Scientist', 'Sales Executive',
       'Sales Representative'],
      dtype='object')

In [466]:
df.JobSatisfaction.unique()

array([4., 3., 2., 1.])

In [467]:
df.MaritalStatus.unique()

array(['Married', 'Single', 'Divorced'], dtype=object)

In [468]:
df = df.join(pd.get_dummies(df["MaritalStatus"], drop_first=True)).drop("MaritalStatus", axis=1)

In [469]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition',
       'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales', 'Life Sciences', 'Marketing',
       'Medical', 'Other', 'Technical Degree', 'Human Resources',
       'Laboratory Technician', 'Manager', 'Manufacturing Director',
       'Research Director', 'Research Scientist', 'Sales Executive',
       'Sales Representative', 'Married', 'Single'],
      dtype='object')

In [470]:
df.MonthlyIncome.unique()

array([ 5126.,  7756.,  2368., ..., 13570., 13348.,  3708.])

In [471]:
df.MonthlyRate.unique()

array([15998., 14199., 23300., ...,  5640., 14842.,  2104.])

In [472]:
df.NumCompaniesWorked.unique()

array([1., 3., 0., 5., 9., 4., 2., 6., 7., 8.])

In [473]:
df.Over18.unique()

array(['Y'], dtype=object)

In [474]:
df = df.drop("Over18", axis=1)

In [475]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition',
       'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales', 'Life Sciences', 'Marketing',
       'Medical', 'Other', 'Technical Degree', 'Human Resources',
       'Laboratory Technician', 'Manager', 'Manufacturing Director',
       'Research Director', 'Research Scientist', 'Sales Executive',
       'Sales Representative', 'Married', 'Single'],
      dtype='object')

In [476]:
df.OverTime.unique()

array(['Yes', 'No'], dtype=object)

In [477]:
df["OverTime"] = [1 if x == "Yes" else 0 for x in df["OverTime"]]

In [478]:
df.OverTime.unique()

array([1, 0])

In [479]:
df.PercentSalaryHike.unique()

array([12., 19., 21., 15., 11., 16., 14., 13., 18., 23., 22., 17., 20.,
       25., 24.])

In [480]:
df.PerformanceRating.unique()

array([3., 4.])

In [481]:
df.RelationshipSatisfaction.unique()

array([3., 4., 2., 1.])

In [482]:
df.StandardHours.unique()

array([80.])

In [483]:
df=df.drop(['StandardHours'],axis=1)

In [484]:
df.StockOptionLevel.unique()

array([2., 1., 0., 3.])

In [485]:
df.TotalWorkingYears.unique()

array([1.000e+01, 5.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 2.100e+01,
       1.100e+01, 1.900e+01, 0.000e+00, 6.000e+00, 2.600e+01, 9.000e+00,
       1.400e+01, 1.700e+01, 2.500e+01, 1.200e+01, 1.300e+01, 7.000e+00,
       8.000e+00, 1.800e+01, 2.800e+01, 1.500e+01, 2.000e+01, 2.300e+01,
       2.400e+01, 1.600e+01, 3.700e+01, 2.200e+01, 4.000e+00, 3.000e+01,
       3.200e+01, 3.100e+01, 2.700e+01, 2.900e+01, 3.500e+01, 3.800e+01,
       3.400e+01, 4.000e+01, 3.600e+01, 3.300e+01, 6.618e+03, 3.808e+03,
       2.764e+03, 4.370e+03, 1.086e+03, 5.377e+03, 8.821e+03, 9.536e+03,
       1.822e+03, 4.740e+03, 3.625e+03, 8.183e+03, 8.890e+03, 9.670e+03,
       9.815e+03, 4.506e+03, 1.442e+03, 4.031e+03, 4.196e+03, 2.450e+03,
       6.907e+03, 8.095e+03, 4.409e+03, 5.482e+03, 9.714e+03, 8.746e+03,
       7.825e+03, 6.463e+03, 1.123e+03, 2.194e+03, 4.607e+03, 7.635e+03,
       9.501e+03, 8.270e+03, 5.787e+03, 4.958e+03, 3.077e+03, 8.575e+03,
       2.270e+03, 4.176e+03, 1.143e+03, 5.257e+03, 

In [486]:
df=df[df['TotalWorkingYears']<= 100]

In [487]:
df.TotalWorkingYears.unique()

array([10.,  5.,  1.,  2.,  3., 21., 11., 19.,  0.,  6., 26.,  9., 14.,
       17., 25., 12., 13.,  7.,  8., 18., 28., 15., 20., 23., 24., 16.,
       37., 22.,  4., 30., 32., 31., 27., 29., 35., 38., 34., 40., 36.,
       33.])

In [488]:
df.TrainingTimesLastYear.unique()

array([1., 6., 3., 0., 4., 2., 5.])

In [489]:
df.WorkLifeBalance.unique()

array([2., 4., 3., 1.])

In [490]:
df.YearsAtCompany.unique()

array([1.000e+01, 5.000e+00, 1.000e+00, 2.000e+00, 7.000e+00, 9.000e+00,
       2.000e+01, 0.000e+00, 3.000e+00, 1.400e+01, 8.000e+00, 2.400e+01,
       6.000e+00, 4.000e+00, 1.100e+01, 1.500e+01, 1.300e+01, 2.100e+01,
       3.600e+01, 2.600e+01, 1.900e+01, 1.600e+01, 2.200e+01, 1.800e+01,
       2.500e+01, 1.700e+01, 1.200e+01, 3.700e+01, 3.300e+01, 4.000e+01,
       3.400e+01, 2.300e+01, 2.900e+01, 3.100e+01, 3.200e+01, 2.700e+01,
       3.000e+01, 5.078e+03, 7.345e+03, 3.079e+03, 2.332e+03, 1.761e+03,
       1.378e+03, 8.870e+03, 4.879e+03, 9.445e+03, 2.265e+03, 5.801e+03,
       8.553e+03, 3.761e+03, 2.051e+03, 7.735e+03, 2.506e+03, 9.066e+03,
       3.335e+03, 1.621e+03, 8.120e+03, 3.743e+03, 9.681e+03, 6.797e+03,
       3.707e+03, 7.547e+03, 6.133e+03, 3.177e+03, 3.549e+03, 8.717e+03,
       1.036e+03, 9.508e+03, 1.488e+03, 5.359e+03, 2.744e+03, 5.581e+03,
       9.676e+03, 1.286e+03, 5.904e+03, 1.872e+03, 4.763e+03, 7.324e+03,
       6.140e+03, 3.687e+03, 1.420e+03, 9.767e+03, 

In [491]:
df=df[df['YearsAtCompany']<= 100]

In [492]:
df.YearsAtCompany.unique()

array([10.,  5.,  1.,  2.,  7.,  9., 20.,  0.,  3., 14.,  8., 24.,  6.,
        4., 11., 15., 13., 21., 36., 26., 19., 16., 22., 18., 25., 17.,
       12., 37., 33., 40., 34., 23., 29., 31., 32., 27., 30.])

In [493]:
df.YearsInCurrentRole.unique()

array([8.000e+00, 4.000e+00, 3.000e+00, 0.000e+00, 2.000e+00, 7.000e+00,
       6.000e+00, 9.000e+00, 5.000e+00, 1.300e+01, 1.100e+01, 1.000e+00,
       1.000e+01, 1.700e+01, 1.200e+01, 1.500e+01, 1.400e+01, 1.600e+01,
       1.800e+01, 3.099e+03, 3.591e+03, 6.908e+03, 1.099e+03, 3.814e+03,
       6.651e+03, 4.218e+03, 1.179e+03, 4.230e+03, 9.454e+03, 5.438e+03,
       2.975e+03, 4.252e+03, 2.939e+03, 9.459e+03, 9.420e+03, 4.139e+03,
       8.200e+03, 2.100e+03, 4.858e+03, 6.364e+03, 8.251e+03, 4.925e+03,
       3.723e+03, 4.194e+03, 4.323e+03, 4.558e+03, 1.858e+03, 7.125e+03,
       4.435e+03, 8.935e+03, 4.986e+03, 9.107e+03, 7.137e+03, 4.656e+03,
       2.515e+03, 7.635e+03, 4.461e+03, 7.908e+03, 5.735e+03, 8.835e+03,
       1.797e+03, 4.137e+03, 9.193e+03, 6.691e+03, 9.596e+03, 7.077e+03,
       1.191e+03, 4.174e+03, 4.713e+03, 3.606e+03, 5.335e+03, 9.822e+03,
       7.420e+03, 2.816e+03, 7.866e+03, 3.509e+03, 2.360e+03, 2.514e+03,
       4.376e+03, 7.320e+03, 3.443e+03, 3.453e+03, 

In [494]:
df=df[df['YearsInCurrentRole']<= 100]

In [495]:
df.YearsInCurrentRole.unique()

array([ 8.,  4.,  3.,  0.,  2.,  7.,  6.,  9.,  5., 13., 11.,  1., 10.,
       17., 12., 15., 14., 16., 18.])

In [496]:
df.YearsSinceLastPromotion.unique()

array([3.000e+00, 0.000e+00, 4.000e+00, 2.000e+00, 7.000e+00, 1.000e+00,
       9.000e+00, 8.000e+00, 5.000e+00, 1.100e+01, 6.000e+00, 1.500e+01,
       1.200e+01, 1.300e+01, 1.400e+01, 1.000e+01, 8.080e+03, 3.720e+03,
       7.291e+03, 6.920e+03, 8.467e+03, 9.420e+03, 3.246e+03, 8.913e+03,
       9.952e+03, 8.550e+03, 7.997e+03, 8.534e+03, 6.773e+03, 4.940e+03,
       1.973e+03, 6.763e+03, 8.021e+03, 5.738e+03, 5.291e+03, 1.094e+03,
       3.771e+03, 4.958e+03, 8.890e+03, 8.538e+03, 3.982e+03, 2.153e+03,
       6.279e+03, 7.240e+03, 4.204e+03, 5.392e+03, 3.486e+03, 3.742e+03,
       6.401e+03, 2.166e+03, 8.312e+03, 5.994e+03, 5.894e+03, 2.293e+03,
       6.747e+03, 7.989e+03, 4.200e+03, 2.754e+03, 8.922e+03, 4.370e+03,
       9.389e+03, 4.704e+03, 1.201e+03, 3.777e+03, 1.815e+03, 4.382e+03,
       2.576e+03, 2.475e+03, 6.551e+03, 9.509e+03, 5.284e+03, 5.292e+03,
       9.990e+03, 6.003e+03, 4.575e+03, 5.649e+03, 2.081e+03, 7.609e+03,
       9.572e+03, 5.308e+03, 5.383e+03, 1.058e+03, 

In [497]:
df=df[df['YearsSinceLastPromotion']<= 100]

In [498]:
df.YearsSinceLastPromotion.unique()

array([ 3.,  0.,  4.,  2.,  7.,  1.,  9.,  8.,  5., 11.,  6., 15., 12.,
       13., 14., 10.])

In [499]:
df.YearsWithCurrManager.unique()

array([0.000e+00, 2.000e+00, 3.000e+00, 7.000e+00, 8.000e+00, 9.000e+00,
       6.000e+00, 1.100e+01, 4.000e+00, 1.200e+01, 5.000e+00, 1.000e+01,
       1.700e+01, 1.000e+00, 1.300e+01, 1.400e+01, 1.600e+01, 1.500e+01,
       1.798e+03, 9.404e+03, 4.163e+03, 2.411e+03, 1.947e+03, 5.987e+03,
       9.201e+03, 5.346e+03, 2.106e+03, 8.731e+03, 1.759e+03, 2.736e+03,
       2.181e+03, 7.012e+03, 6.277e+03, 7.405e+03, 2.101e+03, 3.908e+03,
       1.781e+03, 2.883e+03, 4.389e+03, 7.032e+03, 2.811e+03, 5.256e+03,
       6.162e+03, 5.242e+03, 3.922e+03, 5.168e+03, 8.672e+03, 9.717e+03,
       6.129e+03, 5.048e+03, 3.434e+03, 2.879e+03, 9.333e+03, 2.892e+03,
       4.528e+03, 7.876e+03, 2.702e+03, 6.788e+03, 1.077e+03, 2.428e+03,
       5.233e+03, 8.457e+03, 9.709e+03, 3.546e+03, 9.321e+03, 5.326e+03,
       2.333e+03, 9.882e+03, 2.564e+03, 1.910e+03, 4.869e+03, 2.480e+03,
       8.393e+03, 4.404e+03, 6.426e+03, 8.841e+03, 7.091e+03, 4.220e+03,
       1.540e+03, 6.691e+03, 7.781e+03, 4.321e+03, 

In [500]:
df=df[df['YearsWithCurrManager']<= 100]

In [501]:
df.YearsWithCurrManager.unique()

array([ 0.,  2.,  3.,  7.,  8.,  9.,  6., 11.,  4., 12.,  5., 10., 17.,
        1., 13., 14., 16., 15.])

In [502]:
df.YearlyIncome.unique()

array([ 61512.,  93072.,  28416., ...,  79728., 238308.,  44496.])

In [503]:
df.YearlyIncome.describe()

count      2630.000000
mean      77384.733080
std       56485.757872
min       12108.000000
25%       34404.000000
50%       58260.000000
75%      100347.000000
max      239988.000000
Name: YearlyIncome, dtype: float64

In [504]:
df.shape

(2630, 47)

In [505]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2630 entries, 0 to 4448
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   EmployeeNumber            2630 non-null   int64  
 1   Age                       2630 non-null   float64
 2   DailyRate                 2630 non-null   float64
 3   DistanceFromHome          2630 non-null   float64
 4   Education                 2630 non-null   float64
 5   EnvironmentSatisfaction   2630 non-null   float64
 6   Gender                    2630 non-null   int64  
 7   HourlyRate                2630 non-null   float64
 8   JobInvolvement            2630 non-null   float64
 9   JobLevel                  2630 non-null   float64
 10  JobSatisfaction           2630 non-null   float64
 11  MonthlyIncome             2630 non-null   float64
 12  MonthlyRate               2630 non-null   float64
 13  NumCompaniesWorked        2630 non-null   float64
 14  OverTime

In [506]:
df= df.set_index("EmployeeNumber")

In [507]:
df.shape

(2630, 46)

In [508]:
y = df.pop('Attrition')
X = df