In [2]:
import pandas as pd
import numpy as np

In [16]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import iplot

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
df1 = pd.read_csv('/content/df1.csv')
df1.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  \
0                      4.0    Male        55.0             2.0       2.0   
1                      4.0  Female        54.0             2.0       3.0   
2                      3.0  Female        46.0             2.0       1.0   
3                      4.0  Female        66.0             3.0       1.0   
4                      3.0    Male        75.0             3.0       1.0   

                  JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  \
0   Laboratory Technician              4.0       Married         5126.0   
1  Manufacturing Director              3.0       Married         7756.0   
2      Research Scientist              2.0       Married         2368.0   
3      Research Scientist              4.0        Single         3310.0   
4   Laboratory Technician              4.0      Divorced         1951.0   

   MonthlyRate  NumCompaniesWorked  
0      15998.0                 1.0  
1      14199.0                 3.0  
2      23300.0                 1.0  
3       4488.0                 1.0  
4      10910.0                 1.0

In [5]:
df1.shape

(4449, 20)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4449 entries, 0 to 4448
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   EmployeeNumber           4449 non-null   int64  
 1   Age                      4449 non-null   float64
 2   BusinessTravel           4449 non-null   object 
 3   DailyRate                4449 non-null   float64
 4   Department               4449 non-null   object 
 5   DistanceFromHome         4449 non-null   float64
 6   Education                4449 non-null   float64
 7   EducationField           4449 non-null   object 
 8   EmployeeCount            4449 non-null   float64
 9   EnvironmentSatisfaction  4449 non-null   float64
 10  Gender                   4449 non-null   object 
 11  HourlyRate               4449 non-null   float64
 12  JobInvolvement           4449 non-null   float64
 13  JobLevel                 4449 non-null   float64
 14  JobRole                 

In [6]:
df2 = pd.read_csv('/content/df2.csv')
df2.head()

EmployeeNumber Over18 OverTime  PercentSalaryHike  PerformanceRating  \
0             104      Y      Yes               12.0                3.0   
1            1638      Y      Yes               19.0                3.0   
2             164      Y       No               19.0                3.0   
3             395      Y       No               21.0                4.0   
4              53      Y       No               12.0                3.0   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                       3.0           80.0               2.0   
1                       4.0           80.0               1.0   
2                       3.0           80.0               0.0   
3                       4.0           80.0               0.0   
4                       3.0           80.0               1.0   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0               10.0                    1.0              2.0            10.0   
1               10.0                    6.0              4.0             5.0   
2                5.0                    3.0              2.0             5.0   
3                5.0                    3.0              3.0             5.0   
4                1.0                    3.0              3.0             1.0   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                 8.0                      3.0                   0.0   
1                 4.0                      0.0                   2.0   
2                 4.0                      4.0                   3.0   
3                 3.0                      0.0                   2.0   
4                 0.0                      0.0                   0.0   

  Attrition  YearlyIncome  
0        No       61512.0  
1        No       93072.0  
2        No       28416.0  
3        No       39720.0  
4        No       23412.0

In [7]:
df2.shape

(4449, 17)

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4449 entries, 0 to 4448
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   EmployeeNumber            4449 non-null   int64  
 1   Over18                    4449 non-null   object 
 2   OverTime                  4449 non-null   object 
 3   PercentSalaryHike         4449 non-null   float64
 4   PerformanceRating         4449 non-null   float64
 5   RelationshipSatisfaction  4449 non-null   float64
 6   StandardHours             4449 non-null   float64
 7   StockOptionLevel          4449 non-null   float64
 8   TotalWorkingYears         4449 non-null   float64
 9   TrainingTimesLastYear     4449 non-null   float64
 10  WorkLifeBalance           4449 non-null   float64
 11  YearsAtCompany            4449 non-null   float64
 12  YearsInCurrentRole        4449 non-null   float64
 13  YearsSinceLastPromotion   4449 non-null   float64
 14  YearsWit

In [99]:
df = pd.merge(df1, df2, on='EmployeeNumber')

In [100]:
df.shape

(4449, 36)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4449 entries, 0 to 4448
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   EmployeeNumber            4449 non-null   int64  
 1   Age                       4449 non-null   float64
 2   BusinessTravel            4449 non-null   object 
 3   DailyRate                 4449 non-null   float64
 4   Department                4449 non-null   object 
 5   DistanceFromHome          4449 non-null   float64
 6   Education                 4449 non-null   float64
 7   EducationField            4449 non-null   object 
 8   EmployeeCount             4449 non-null   float64
 9   EnvironmentSatisfaction   4449 non-null   float64
 10  Gender                    4449 non-null   object 
 11  HourlyRate                4449 non-null   float64
 12  JobInvolvement            4449 non-null   float64
 13  JobLevel                  4449 non-null   float64
 14  JobRole 

In [102]:
df.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  ... StockOptionLevel  TotalWorkingYears  \
0                      4.0  ...              2.0               10.0   
1                      4.0  ...              1.0               10.0   
2                      3.0  ...              0.0                5.0   
3                      4.0  ...              0.0                5.0   
4                      3.0  ...              1.0                1.0   

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                    1.0              2.0           10.0                 8.0   
1                    6.0              4.0            5.0                 4.0   
2                    3.0              2.0            5.0                 4.0   
3                    3.0              3.0            5.0                 3.0   
4                    3.0              3.0            1.0                 0.0   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  YearlyIncome  
0                     3.0                   0.0         No       61512.0  
1                     0.0                   2.0         No       93072.0  
2                     4.0                   3.0         No       28416.0  
3                     0.0                   2.0         No       39720.0  
4                     0.0                   0.0         No       23412.0  

[5 rows x 36 columns]

In [103]:
df.Attrition.unique()

array(['No', 'Yes', nan], dtype=object)

In [104]:
df = df.dropna(subset=['Attrition'])

In [105]:
df.Attrition.unique()

array(['No', 'Yes'], dtype=object)

In [106]:
df.shape

(4302, 36)

In [107]:
Attrition_dict = {'No':0, 'Yes':1}
df['Attrition']=df['Attrition'].map(Attrition_dict)

In [108]:
df.Attrition.unique()

array([0, 1])

In [109]:
df.Age.unique()

array([  30.,   38.,   26.,   28.,   35.,   34.,   32.,   42.,   40.,
         48.,   39.,   18.,   43.,   21.,   53.,   45.,   29.,   33.,
         41.,   24.,   37.,   50.,   36.,   52.,   47.,   31.,   49.,
         54.,   44.,   22.,   46.,   27.,   55.,   59.,   25.,   23.,
         56.,   20.,   60.,   51.,   58.,   19.,   57., 8825., 3628.,
       6287., 9330., 1107., 4454., 9155., 9890., 1189., 9195., 9014.,
       1136., 5582., 2404., 1541., 4510., 4322., 4988., 8388., 2530.,
       8901., 2852., 2459., 2982., 4973., 8534., 8314., 4130., 4328.,
       7952., 8699., 3147., 8889., 3871., 9531., 8167., 5257., 8136.,
       7390., 2993., 5672., 5933., 5614., 5007., 3095., 9219., 6749.,
       4515., 6715., 1141., 8949., 3636., 4805., 5959., 9384., 8042.,
       1423., 7056., 5116., 2667., 8703., 1126., 9612., 7845., 6998.,
       1788., 6727., 5377., 5565., 4558., 6506., 4591., 7662., 6510.,
       4985., 9581., 2095., 2275., 6399., 4935., 2698., 7617., 9661.,
       4834., 2242.,

In [110]:
df = df[df['Age'] <= 100]

In [111]:
df.Age.unique()

array([30., 38., 26., 28., 35., 34., 32., 42., 40., 48., 39., 18., 43.,
       21., 53., 45., 29., 33., 41., 24., 37., 50., 36., 52., 47., 31.,
       49., 54., 44., 22., 46., 27., 55., 59., 25., 23., 56., 20., 60.,
       51., 58., 19., 57.])

In [112]:
df.BusinessTravel.unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [113]:
df = df.join(pd.get_dummies(df["BusinessTravel"], drop_first=True)).drop("BusinessTravel", axis=1)

In [114]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'YearlyIncome',
       'Travel_Frequently', 'Travel_Rarely'],
      dtype='object')

In [115]:
df.DailyRate.unique()

array([ 852.,  397.,  841., 1117.,  464., 1107., 1018.,  269.,  296.,
        989.,  855., 1181.,  895.,  827.,  977.,  544.,  244.,  995.,
       1343., 1282.,  153.,  280.,  404., 1265.,  252., 1496.,  306.,
        128.,  529.,  553.,  572.,  482.,  471.,  509.,  130.,  506.,
        329.,  367., 1219.,  746., 1322.,  969., 1271., 1158.,  688.,
        319.,  371., 1336.,  107.,  448.,  359.,  625., 1017.,  835.,
       1050.,  523., 1064., 1128.,  928., 1319.,  932.,  809., 1376.,
        253.,  336.,  884., 1385.,  945.,  118., 1231.,  426.,  737.,
       1442.,  853.,  557.,  377.,  616., 1398., 1138.,  531.,  138.,
       1377., 1240., 1400., 1001., 1082., 1171.,  136.,  218.,  452.,
       1397., 1192.,  944.,  408., 1040., 1329., 1416., 1125., 1144.,
        442., 1157.,  438.,  147.,  140.,  240.,  202., 1297.,  486.,
       1146.,  150., 1404., 1206., 1172.,  771., 1167.,  441., 1141.,
        715.,  891.,  282., 1425., 1371.,  170.,  650., 1212.,  638.,
       1255., 1099.,

In [116]:
df.Department.unique()

array(['Research & Development', 'Human Resources', 'Sales'], dtype=object)

In [117]:
df = df.join(pd.get_dummies(df["Department"], drop_first=True)).drop("Department", axis=1)

In [118]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EducationField', 'EmployeeCount', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition',
       'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales'],
      dtype='object')

In [119]:
df.DistanceFromHome.unique()

array([1.00000e+00, 2.00000e+00, 6.00000e+00, 8.00000e+00, 4.00000e+00,
       9.00000e+00, 3.00000e+00, 5.00000e+00, 2.20000e+01, 2.60000e+01,
       1.00000e+01, 1.20000e+01, 7.00000e+00, 2.50000e+01, 2.90000e+01,
       1.80000e+01, 2.40000e+01, 2.80000e+01, 1.60000e+01, 1.90000e+01,
       1.30000e+01, 2.00000e+01, 1.10000e+01, 2.30000e+01, 2.10000e+01,
       1.50000e+01, 1.40000e+01, 1.70000e+01, 2.70000e+01, 3.02984e+05,
       6.29986e+05, 8.87003e+05, 9.18326e+05, 9.97422e+05, 8.52749e+05,
       6.79106e+05, 3.04698e+05, 7.72706e+05, 2.59089e+05, 9.92947e+05,
       2.53620e+05, 8.86117e+05, 8.60358e+05, 5.47308e+05, 1.93929e+05,
       9.63929e+05, 8.09361e+05, 1.40916e+05, 8.25100e+05, 4.18093e+05,
       7.16417e+05, 5.46730e+05, 2.42839e+05, 7.43173e+05, 1.50886e+05,
       9.46786e+05, 6.07220e+05, 5.60047e+05, 8.40183e+05, 5.88585e+05,
       4.79723e+05, 3.02239e+05, 9.99590e+05, 1.35607e+05, 3.27380e+05,
       5.16738e+05, 3.80120e+05, 2.89540e+05, 4.70836e+05, 6.364

In [120]:
df.Education.unique()

array([1., 2., 3., 4., 5.])

In [121]:
df.EducationField.unique()

array(['Life Sciences', 'Medical', 'Other', 'Technical Degree',
       'Marketing', 'Human Resources'], dtype=object)

In [122]:
df = df.join(pd.get_dummies(df["EducationField"], drop_first=True)).drop("EducationField", axis=1)

In [123]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EmployeeCount', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'YearlyIncome',
       'Travel_Frequently', 'Travel_Rarely', 'Research & Development', 'Sales',
       'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree'],
      dtype='object')

In [124]:
df.EmployeeCount.unique()

array([1.])

In [125]:
df = df.drop(['EmployeeCount'] ,axis=1)

In [126]:
df.EnvironmentSatisfaction.unique()

array([4., 3., 1., 2.])

In [127]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [128]:
Gender_dict = {'Male':0, 'Female':1}
df['Gender']=df['Gender'].map(Gender_dict)

In [129]:
df.Gender.unique()

array([0, 1])

In [130]:
df.HourlyRate.unique()

array([ 55.,  54.,  46.,  66.,  75.,  52.,  39.,  56.,  33.,  82.,  45.,
        70.,  97.,  77.,  40.,  49.,  58.,  73.,  43.,  98.,  95.,  41.,
       100.,  84.,  79.,  74.,  90.,  96.,  91.,  32.,  88.,  86.,  76.,
        35.,  94.,  83.,  65.,  42.,  31.,  51.,  36.,  80.,  69.,  99.,
        48.,  89.,  81.,  61.,  92.,  59.,  44.,  47.,  53.,  34.,  60.,
        78.,  30.,  68.,  37.,  87.,  50.,  63.,  72.,  38.,  71.,  64.,
        85.,  57.,  67.,  62.,  93.])

In [131]:
df.JobInvolvement.unique()

array([2., 3., 1., 4.])

In [132]:
df.JobLevel.unique()

array([2., 3., 1., 5., 4.])

In [133]:
df.JobRole.unique()

array(['Laboratory Technician', 'Manufacturing Director',
       'Research Scientist', 'Human Resources', 'Research Director',
       'Sales Representative', 'Manager', 'Healthcare Representative',
       'Sales Executive'], dtype=object)

In [140]:
df = df.join(pd.get_dummies(df["JobRole"], drop_first=True)).drop("JobRole", axis=1)

In [141]:
df.columns

Index(['EmployeeNumber', 'Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'Attrition', 'YearlyIncome', 'Travel_Frequently', 'Travel_Rarely',
       'Research & Development', 'Sales', 'Life Sciences', 'Marketing',
       'Medical', 'Other', 'Technical Degree',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research

In [142]:
df.JobSatisfaction.unique()

array([4., 3., 2., 1.])