In [51]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from plotly.offline import iplot
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.tree import DecisionTreeRegressor
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats
from sklearn.metrics import r2_score
from sklearn import tree
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import LeaveOneOut
from IPython.display import display
df1 = pd.read_csv('df1.csv')
df2 = pd.read_csv('df2.csv')

In [52]:
df1.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  \
0                      4.0    Male        55.0             2.0       2.0   
1                      4.0  Female        54.0             2.0       3.0   
2                      3.0  Female        46.0             2.0       1.0   
3                      4.0  Female        66.0             3.0       1.0   
4                      3.0    Male        75.0             3.0       1.0   

                  JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  \
0   Laboratory Technician              4.0       Married         5126.0   
1  Manufacturing Director              3.0       Married         7756.0   
2      Research Scientist              2.0       Married         2368.0   
3      Research Scientist              4.0        Single         3310.0   
4   Laboratory Technician              4.0      Divorced         1951.0   

   MonthlyRate  NumCompaniesWorked  
0      15998.0                 1.0  
1      14199.0                 3.0  
2      23300.0                 1.0  
3       4488.0                 1.0  
4      10910.0                 1.0

In [53]:
df2.head()

EmployeeNumber Over18 OverTime  PercentSalaryHike  PerformanceRating  \
0             104      Y      Yes               12.0                3.0   
1            1638      Y      Yes               19.0                3.0   
2             164      Y       No               19.0                3.0   
3             395      Y       No               21.0                4.0   
4              53      Y       No               12.0                3.0   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                       3.0           80.0               2.0   
1                       4.0           80.0               1.0   
2                       3.0           80.0               0.0   
3                       4.0           80.0               0.0   
4                       3.0           80.0               1.0   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0               10.0                    1.0              2.0            10.0   
1               10.0                    6.0              4.0             5.0   
2                5.0                    3.0              2.0             5.0   
3                5.0                    3.0              3.0             5.0   
4                1.0                    3.0              3.0             1.0   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                 8.0                      3.0                   0.0   
1                 4.0                      0.0                   2.0   
2                 4.0                      4.0                   3.0   
3                 3.0                      0.0                   2.0   
4                 0.0                      0.0                   0.0   

  Attrition  YearlyIncome  
0        No       61512.0  
1        No       93072.0  
2        No       28416.0  
3        No       39720.0  
4        No       23412.0

In [54]:
df = pd.merge(df1, df2, on='EmployeeNumber') # łączymy bazy danych w jedną całość 

In [55]:
df.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  ... StockOptionLevel  TotalWorkingYears  \
0                      4.0  ...              2.0               10.0   
1                      4.0  ...              1.0               10.0   
2                      3.0  ...              0.0                5.0   
3                      4.0  ...              0.0                5.0   
4                      3.0  ...              1.0                1.0   

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                    1.0              2.0           10.0                 8.0   
1                    6.0              4.0            5.0                 4.0   
2                    3.0              2.0            5.0                 4.0   
3                    3.0              3.0            5.0                 3.0   
4                    3.0              3.0            1.0                 0.0   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  YearlyIncome  
0                     3.0                   0.0         No       61512.0  
1                     0.0                   2.0         No       93072.0  
2                     4.0                   3.0         No       28416.0  
3                     0.0                   2.0         No       39720.0  
4                     0.0                   0.0         No       23412.0  

[5 rows x 36 columns]

In [56]:
df.columns # sprawdzamy kolumny i dzielimy kto ma jaką ogarnąć

Index(['EmployeeNumber', 'Age', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'YearlyIncome'],
      dtype='object')

In [57]:
df.RelationshipSatisfaction.unique()

array([3., 4., 2., 1.])

In [58]:
df.StandardHours.unique() # jest tu jedna warotść, kolumna będzie do usunięcia

array([80.])

In [59]:
df.StockOptionLevel.unique()

array([2., 1., 0., 3.])

In [60]:
df.TotalWorkingYears.unique()

array([1.000e+01, 5.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 2.100e+01,
       1.100e+01, 1.900e+01, 0.000e+00, 6.000e+00, 2.600e+01, 9.000e+00,
       1.400e+01, 1.700e+01, 2.500e+01, 1.200e+01, 1.300e+01, 7.000e+00,
       8.000e+00, 1.800e+01, 2.800e+01, 1.500e+01, 2.000e+01, 2.300e+01,
       2.400e+01, 1.600e+01, 3.700e+01, 2.200e+01, 4.000e+00, 3.000e+01,
       3.200e+01, 3.100e+01, 2.700e+01, 2.900e+01, 3.500e+01, 3.800e+01,
       3.400e+01, 4.000e+01, 3.600e+01, 3.300e+01, 6.618e+03, 3.808e+03,
       2.764e+03, 4.370e+03, 1.086e+03, 5.377e+03, 8.821e+03, 9.536e+03,
       1.822e+03, 4.740e+03, 3.625e+03, 8.183e+03, 8.890e+03, 9.670e+03,
       9.815e+03, 4.506e+03, 1.442e+03, 4.031e+03, 4.196e+03, 2.450e+03,
       6.907e+03, 8.095e+03, 4.409e+03, 5.482e+03, 9.714e+03, 8.746e+03,
       7.825e+03, 6.463e+03, 1.123e+03, 2.194e+03, 4.607e+03, 7.635e+03,
       9.501e+03, 8.270e+03, 5.787e+03, 4.958e+03, 3.077e+03, 8.575e+03,
       2.270e+03, 4.176e+03, 1.143e+03, 5.257e+03, 

In [61]:
df.TrainingTimesLastYear.unique()

array([1., 6., 3., 0., 4., 2., 5.])

In [62]:
df.WorkLifeBalance.unique()

array([2., 4., 3., 1.])

In [63]:
df.YearsAtCompany.unique()

array([1.000e+01, 5.000e+00, 1.000e+00, 2.000e+00, 7.000e+00, 9.000e+00,
       2.000e+01, 0.000e+00, 3.000e+00, 1.400e+01, 8.000e+00, 2.400e+01,
       6.000e+00, 4.000e+00, 1.100e+01, 1.500e+01, 1.300e+01, 2.100e+01,
       3.600e+01, 2.600e+01, 1.900e+01, 1.600e+01, 2.200e+01, 1.800e+01,
       2.500e+01, 1.700e+01, 1.200e+01, 3.700e+01, 3.300e+01, 4.000e+01,
       3.400e+01, 2.300e+01, 2.900e+01, 3.100e+01, 3.200e+01, 2.700e+01,
       3.000e+01, 5.078e+03, 7.345e+03, 3.079e+03, 2.332e+03, 1.761e+03,
       1.378e+03, 8.870e+03, 4.879e+03, 9.445e+03, 2.265e+03, 5.801e+03,
       8.553e+03, 3.761e+03, 2.051e+03, 7.735e+03, 2.506e+03, 9.066e+03,
       3.335e+03, 1.621e+03, 8.120e+03, 3.743e+03, 9.681e+03, 6.797e+03,
       3.707e+03, 7.547e+03, 6.133e+03, 3.177e+03, 3.549e+03, 8.717e+03,
       1.036e+03, 9.508e+03, 1.488e+03, 5.359e+03, 2.744e+03, 5.581e+03,
       9.676e+03, 1.286e+03, 5.904e+03, 1.872e+03, 4.763e+03, 7.324e+03,
       6.140e+03, 3.687e+03, 1.420e+03, 9.767e+03, 

In [64]:
df.YearsInCurrentRole.unique()

array([8.000e+00, 4.000e+00, 3.000e+00, 0.000e+00, 2.000e+00, 7.000e+00,
       6.000e+00, 9.000e+00, 5.000e+00, 1.300e+01, 1.100e+01, 1.000e+00,
       1.000e+01, 1.700e+01, 1.200e+01, 1.500e+01, 1.400e+01, 1.600e+01,
       1.800e+01, 3.099e+03, 3.591e+03, 6.908e+03, 1.099e+03, 3.814e+03,
       6.651e+03, 4.218e+03, 1.179e+03, 4.230e+03, 9.454e+03, 5.438e+03,
       2.975e+03, 4.252e+03, 2.939e+03, 9.459e+03, 9.420e+03, 4.139e+03,
       8.200e+03, 2.100e+03, 4.858e+03, 6.364e+03, 8.251e+03, 4.925e+03,
       3.723e+03, 4.194e+03, 4.323e+03, 4.558e+03, 1.858e+03, 7.125e+03,
       4.435e+03, 8.935e+03, 4.986e+03, 9.107e+03, 7.137e+03, 4.656e+03,
       2.515e+03, 7.635e+03, 4.461e+03, 7.908e+03, 5.735e+03, 8.835e+03,
       1.797e+03, 4.137e+03, 9.193e+03, 6.691e+03, 9.596e+03, 7.077e+03,
       1.191e+03, 4.174e+03, 4.713e+03, 3.606e+03, 5.335e+03, 9.822e+03,
       7.420e+03, 2.816e+03, 7.866e+03, 3.509e+03, 2.360e+03, 2.514e+03,
       4.376e+03, 7.320e+03, 3.443e+03, 3.453e+03, 

In [65]:
df.YearsSinceLastPromotion.unique()

array([3.000e+00, 0.000e+00, 4.000e+00, 2.000e+00, 7.000e+00, 1.000e+00,
       9.000e+00, 8.000e+00, 5.000e+00, 1.100e+01, 6.000e+00, 1.500e+01,
       1.200e+01, 1.300e+01, 1.400e+01, 1.000e+01, 8.080e+03, 3.720e+03,
       7.291e+03, 6.920e+03, 8.467e+03, 9.420e+03, 3.246e+03, 8.913e+03,
       9.952e+03, 8.550e+03, 7.997e+03, 8.534e+03, 6.773e+03, 4.940e+03,
       1.973e+03, 6.763e+03, 8.021e+03, 5.738e+03, 5.291e+03, 1.094e+03,
       3.771e+03, 4.958e+03, 8.890e+03, 8.538e+03, 3.982e+03, 2.153e+03,
       6.279e+03, 7.240e+03, 4.204e+03, 5.392e+03, 3.486e+03, 3.742e+03,
       6.401e+03, 2.166e+03, 8.312e+03, 5.994e+03, 5.894e+03, 2.293e+03,
       6.747e+03, 7.989e+03, 4.200e+03, 2.754e+03, 8.922e+03, 4.370e+03,
       9.389e+03, 4.704e+03, 1.201e+03, 3.777e+03, 1.815e+03, 4.382e+03,
       2.576e+03, 2.475e+03, 6.551e+03, 9.509e+03, 5.284e+03, 5.292e+03,
       9.990e+03, 6.003e+03, 4.575e+03, 5.649e+03, 2.081e+03, 7.609e+03,
       9.572e+03, 5.308e+03, 5.383e+03, 1.058e+03, 

In [66]:
df.YearsWithCurrManager.unique()

array([0.000e+00, 2.000e+00, 3.000e+00, 7.000e+00, 8.000e+00, 9.000e+00,
       6.000e+00, 1.100e+01, 4.000e+00, 1.200e+01, 5.000e+00, 1.000e+01,
       1.700e+01, 1.000e+00, 1.300e+01, 1.400e+01, 1.600e+01, 1.500e+01,
       1.798e+03, 9.404e+03, 4.163e+03, 2.411e+03, 1.947e+03, 5.987e+03,
       9.201e+03, 5.346e+03, 2.106e+03, 8.731e+03, 1.759e+03, 2.736e+03,
       2.181e+03, 7.012e+03, 6.277e+03, 7.405e+03, 2.101e+03, 3.908e+03,
       1.781e+03, 2.883e+03, 4.389e+03, 7.032e+03, 2.811e+03, 5.256e+03,
       6.162e+03, 5.242e+03, 3.922e+03, 5.168e+03, 8.672e+03, 9.717e+03,
       6.129e+03, 5.048e+03, 3.434e+03, 2.879e+03, 9.333e+03, 2.892e+03,
       4.528e+03, 7.876e+03, 2.702e+03, 6.788e+03, 1.077e+03, 2.428e+03,
       5.233e+03, 8.457e+03, 9.709e+03, 3.546e+03, 9.321e+03, 5.326e+03,
       2.333e+03, 9.882e+03, 2.564e+03, 1.910e+03, 4.869e+03, 2.480e+03,
       8.393e+03, 4.404e+03, 6.426e+03, 8.841e+03, 7.091e+03, 4.220e+03,
       1.540e+03, 6.691e+03, 7.781e+03, 4.321e+03, 

In [67]:
df.Attrition.unique() # tutaj usuniemy nany 

array(['No', 'Yes', nan], dtype=object)

In [68]:
df['YearlyIncome']

0       61512.0
1       93072.0
2       28416.0
3       39720.0
4       23412.0
         ...   
4444    95736.0
4445    95736.0
4446    44496.0
4447    44496.0
4448    44496.0
Name: YearlyIncome, Length: 4449, dtype: float64

In [69]:
df=df.drop(['StandardHours'],axis=1) #usuwamy kolumne ze względu na jedna wartość
df=df[df['TotalWorkingYears']<= 100] # usuwamy lata, które są wiecej niz 100
df=df[df['YearsAtCompany']<= 100] # usuwamy lata, które są więcej niż 100
df=df[df['YearsInCurrentRole']<= 100] # to samo
df=df[df['YearsSinceLastPromotion']<= 100] # to samo 
df=df[df['YearsWithCurrManager']<= 100] # to samo
df=df.dropna(subset=['Attrition']) # usuwamy nany z kolumny Attrition

In [70]:
df.head()

EmployeeNumber   Age BusinessTravel  DailyRate              Department  \
0             104  30.0  Travel_Rarely      852.0  Research & Development   
1            1638  38.0  Travel_Rarely      397.0  Research & Development   
2             164  26.0  Travel_Rarely      841.0  Research & Development   
3             395  28.0  Travel_Rarely     1117.0  Research & Development   
4              53  35.0  Travel_Rarely      464.0  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  \
0               1.0        1.0  Life Sciences            1.0   
1               2.0        2.0        Medical            1.0   
2               6.0        3.0          Other            1.0   
3               8.0        2.0  Life Sciences            1.0   
4               4.0        2.0          Other            1.0   

   EnvironmentSatisfaction  ... StockOptionLevel  TotalWorkingYears  \
0                      4.0  ...              2.0               10.0   
1                      4.0  ...              1.0               10.0   
2                      3.0  ...              0.0                5.0   
3                      4.0  ...              0.0                5.0   
4                      3.0  ...              1.0                1.0   

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                    1.0              2.0           10.0                 8.0   
1                    6.0              4.0            5.0                 4.0   
2                    3.0              2.0            5.0                 4.0   
3                    3.0              3.0            5.0                 3.0   
4                    3.0              3.0            1.0                 0.0   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  YearlyIncome  
0                     3.0                   0.0         No       61512.0  
1                     0.0                   2.0         No       93072.0  
2                     4.0                   3.0         No       28416.0  
3                     0.0                   2.0         No       39720.0  
4                     0.0                   0.0         No       23412.0  

[5 rows x 35 columns]